export enum Config {
  SEED = "SISENSE",
  OCCUPANCY_MIN_POSITIVE = 1,
  TIME_SLOT_LOWER_BOUNDARY = 55,
  TIME_SLOT_UPPER_BOUNDARY = 108,
  HEADCOUNT_NEGATIVE_DEVIANCE = -3,
  HEADCOUNT_POSITIVE_DEVIANCE = 3,
  CAPACITY_MINIMUM = 1,
  CAPACITY_MAXIMUM_DEVIANCE = 3,
}
